[build]
  publish = "."

# Uncomment below to add custom redirects
# [[redirects]]
#   from = "/"
#   to = "/janus.html"
#   status = 200

[[redirects]]
  from = "/"
  to = "/tt.html"
  status = 200

[[redirects]]
  from = "/janus"
  to = "/janus.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/pay"
  to = "https://buy.stripe.com/test_9B66oJ0zp4pR1t4eM52VG00"
  status = 302

# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301 